export const PERFORMANCE_ITEMS = [
  {
    id: '240409si01',
    title: '시스템 개발 프로젝트명',
    img: '',
    labelEn: 'si',
    labelKr: '시스템 개발',
    type: 'major',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409chart',
    title: '해도제작 프로젝트명',
    img: '',
    labelEn: 'chart',
    labelKr: '해도제작',
    type: 'major',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409satel',
    title: '위성 데이터 프로젝트명',
    img: '',
    labelEn: 'satellite',
    labelKr: '위성 데이터',
    type: 'major',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409media',
    title: '해양예보방송 프로젝트명',
    img: '',
    labelEn: 'media',
    labelKr: '해양예보방송',
    type: 'major',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409rnd',
    title: '연구사업 프로젝트명',
    img: '',
    labelEn: 'rnd',
    labelKr: '연구사업',
    type: 'major',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409si02',
    title: '개발 프로젝트명',
    img: '',
    labelEn: 'si',
    labelKr: '시스템 개발',
    type: 'all',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409si03',
    title: '해도제작 프로젝트명',
    img: '',
    labelEn: 'chart',
    labelKr: '해도제작',
    type: 'all',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409si04',
    title: '위성 프로젝트명',
    img: '',
    labelEn: 'satellite',
    labelKr: '위성 데이터',
    type: 'all',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409si05',
    title: '해양예보방송 프로젝트명',
    img: '',
    labelEn: 'media',
    labelKr: '해양예보방송',
    type: 'all',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
  {
    id: '240409si06',
    title: '연구사업 프로젝트명',
    img: '',
    labelEn: 'rnd',
    labelKr: '연구사업',
    type: 'all',
    period: '2023년 3월 ~ 12월',
    content: {
      client: '발주처명',
      work: '추진 업무 내용 기술',
      skill: '사용 기술 및 스펙 작성',
    },
  },
]

export default PERFORMANCE_ITEMS
