export const RECRUIT_ITEMS = [
  {
    id: 20240502,
    status: true,
    en: 'open',
    kr: '모집 중',
    title: '모집공고명',
    startDate: '2024년 6월 10일',
    endDate: '모집시 마감',
    personnel: 2,
    capa: '초대졸, 신입, 경력 무관',
    link: '/',
  },
  {
    id: 20240507,
    status: true,
    en: 'open',
    kr: '모집 중',
    title: '모집공고명',
    startDate: '2024년 6월 10일',
    endDate: '모집시 마감',
    personnel: 2,
    capa: '초대졸, 신입, 경력 무관',
    link: '/',
  },
  {
    id: 20240506,
    status: false,
    en: 'close',
    kr: '모집 마감',
    title: '모집공고명',
    startDate: '2023년 3월 13일',
    endDate: '모집시 마감',
    personnel: 2,
    capa: '2년 이상 경력',
    link: null,
  },
  {
    id: 20240503,
    status: false,
    en: 'close',
    kr: '모집 마감',
    title: '모집공고명',
    startDate: '2023년 3월 13일',
    endDate: '모집시 마감',
    personnel: 2,
    capa: '2년 이상 경력',
    link: null,
  },
]

export default RECRUIT_ITEMS
